# Paths included in the module backup (state/environment is always included).
#   state/passwords.env   admin key, foundryvtt.com password, license key, release URL
#   foundryvtt-data       worlds, systems, modules, assets and the cached Foundry release
state/passwords.env
volumes/foundryvtt-data
