#!/usr/bin/env python3

#
# Copyright (C) 2026 tebbi
# SPDX-License-Identifier: GPL-3.0-or-later
#

# Create the (still empty) secrets file with mode 0600. The admin key, the
# foundryvtt.com password, the license key and the presigned release URL are
# written to it by configure-module; they must not be stored in
# state/environment, which NS8 mirrors to Redis in plain text.

import modsecrets

modsecrets.ensure({})
