#!/usr/bin/env python3

#
# Copyright (C) 2026 tebbi
# SPDX-License-Identifier: GPL-3.0-or-later
#

# Return the current configuration for the UI. Secrets (passwords, license key)
# are reported only as booleans so the settings page can show "set / not set"
# without echoing the value back.

import os
import sys
import json

import agent
import modsecrets

_secrets = modsecrets.read()

host = os.getenv("TRAEFIK_HOST", "")

auth_method = "release_url" if _secrets.get("FOUNDRY_RELEASE_URL") else "credentials"

config = {
    "host": host,
    "http2https": os.getenv("TRAEFIK_HTTP2HTTPS") == "True",
    "lets_encrypt": agent.get_route(os.environ["MODULE_ID"]).get("lets_encrypt", False),
    "auth_method": auth_method,
    "foundry_username": os.getenv("FOUNDRY_USERNAME", ""),
    "foundry_version": os.getenv("FOUNDRY_VERSION", ""),
    "timezone": os.getenv("TZ", "UTC"),
    "admin_key_set": bool(_secrets.get("FOUNDRY_ADMIN_KEY")),
    "foundry_password_set": bool(_secrets.get("FOUNDRY_PASSWORD")),
    "release_url_set": bool(_secrets.get("FOUNDRY_RELEASE_URL")),
    "license_key_set": bool(_secrets.get("FOUNDRY_LICENSE_KEY")),
    "url": f"https://{host}/" if host else "",
}

json.dump(config, fp=sys.stdout)
